services:
  backend:
    build:
      context: ./backend_django
      dockerfile: Dockerfile
    container_name: backend_django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend_django:/app
    ports:
      - "8000:8000"
    env_file:
      - ./backend_django/.env

  frontend:
    build:
      context: ./frontend-nextjs
      dockerfile: Dockerfile
    container_name: nextjs_frontend
    volumes:
      - ./frontend-nextjs:/app
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
